{
 "title": "Main dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "server", "query": "artillery-api" },
   {
    "name": "container",
    "query": "1c23-tp-1_node_1, 1c23-tp-1_node_2, 1c23-tp-1_node_3, 1c23-tp-1_cadvisor_1, 1c23-tp-1_grafana_1, 1c23-tp-1_graphite_1,  1c23-tp-1_nginx_1, 1c23-tp-1_bbox_1"
   }
  ]
 },
 "panels": [
  {
   "title": "Scenarios launched (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "target": "alias(stats.gauges.$server.scenarioCounts.Ping_-ping, 'Ping')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioCounts.Metar_with_redis-metar, 'Metar')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioCounts.Spaceflight_News_with_redis-spaceflight_news, 'Spaceflight')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioCounts.Quote_-quote, 'Quote')"
    }
   ]
  },
  {
   "title": "Requests state (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(stats.gauges.$server.codes.500, 'Error')"
    },
    {
     "target": "alias(stats.gauges.$server.codes.200, 'Completed')"
    },
    {
     "target": "alias(stats.gauges.$server.pendingRequests, 'Pending')"
    },
    {
     "target": "alias(stats.gauges.$server.$container.ETIMEDOUT, 'Limited')"
    }
   ]
  },
  {
   "title": "Endpoint response time (server-side)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(add(stats.gauges.customMetric.ping, 0.302), 'Ping')"
    },
    {
     "target": "alias(add(stats.gauges.customMetric.metar, 0.314), 'Metar')"
    },
    {
     "target": "alias(add(stats.gauges.customMetric.spaceflight_news, 0.341), 'Spaceflight')"
    },
    {
     "target": "alias(stats.gauges.customMetric.quote, 'Quote')"
    }
   ]
  },
  {
   "title": "API response time ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(stats.gauges.customMetric.metar_time_request, 'Metar')"
    },
    {
     "target": "alias(stats.gauges.customMetric.spaceflight_news_time_request, 'Spaceflight')"
    },
    {
     "target": "alias(stats.gauges.customMetric.quote_time_request, 'Quote')"
    }
   ]
  },
  {
   "title": "Response time combined (client-side)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.max, 'Upper')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.median, 'Median')"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.2c23-tp-1-node-1.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU')"
    },
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.2c23-tp-1-node-1.memory_usage, 10000000000), 'Memory')"
    },
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.2c23-tp-1-node1-1.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU node1')"
    },
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.2c23-tp-1-node1-1.memory_usage, 10000000000), 'Memory node1')"
    },
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.2c23-tp-1-node2-1.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU node2')"
    },
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.2c23-tp-1-node2-1.memory_usage, 10000000000), 'Memory node2')"
    },
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.2c23-tp-1-node3-1.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU node3')"
    },
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.2c23-tp-1-node3-1.memory_usage, 10000000000), 'Memory node3')"
    }
   ]
  }
 ]
}