{
 "title": "Main dashboard 2",
 "time": { "from": "now-3m", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "query": "artillery-api" },
   {
    "name": "container",
    "query": "1c23-tp-1_node_1, 1c23-tp-1_node_2, 1c23-tp-1_node_3, 1c23-tp-1_cadvisor_1, 1c23-tp-1_grafana_1, 1c23-tp-1_graphite_1,  1c23-tp-1_nginx_1, 1c23-tp-1_bbox_1"
   }
  ]
 },
 "panels": [
  {
   "title": "Scenarios launched (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "target": "alias(stats.gauges.$server.scenarioCounts.Ping_-ping, 'Ping')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioCounts.Metar_-metar, 'Metar')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioCounts.Spaceflight_News_-spaceflight_news, 'Spaceflight')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioCounts.Quote_-quote, 'Quote')"
    }
   ]
  },
  {
   "title": "Requests state (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.$server.errors.*), 'Errored')"
    },
    {
     "target": "alias(stats.gauges.$server.codes.200, 'Completed')"
    },
    {
     "target": "alias(stats.gauges.$server.pendingRequests, 'Pending')"
    },
    {
     "target": "alias(stats.gauges.$server.codes.429, 'Limited')"
    }
   ]
  },
  {
   "title": "Max endpoint response time (server-side)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(stats.*.customMetric.ping.upper, 'Ping')"
    },
    {
     "target": "alias(stats.*.customMetric.metar.upper, 'Metar')"
    },
    {
     "target": "alias(stats.*.customMetric.spaceflight_news.upper, 'Spaceflight')"
    },
    {
     "target": "alias(stats.*.customMetric.quote.upper, 'Quote')"
    }
   ]
  },
  {
   "title": "Mean endpoint response time (server-side)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(stats.*.customMetric.ping.mean, 'Ping')"
    },
    {
     "target": "alias(stats.*.customMetric.metar.mean, 'Metar')"
    },
    {
     "target": "alias(stats.*.customMetric.spaceflight_news.mean, 'Spaceflight')"
    },
    {
     "target": "alias(stats.*.customMetric.quote.mean, 'Quote')"
    }
   ]
  },
  {
   "title": "Max API response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(stats.*.customMetric.metar_time_request.upper, 'Metar')"
    },
    {
     "target": "alias(stats.*.customMetric.spaceflight_news_time_request.upper, 'Spaceflight')"
    },
    {
     "target": "alias(stats.*.customMetric.quote_time_request.upper, 'Quote')"
    }
   ]
  },
  {
   "title": "Mean API response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(stats.*.customMetric.metar_time_request.mean, 'Metar')"
    },
    {
     "target": "alias(stats.*.customMetric.spaceflight_news_time_request.mean, 'Spaceflight')"
    },
    {
     "target": "alias(stats.*.customMetric.quote_time_request.mean, 'Quote')"
    }
   ]
  },
  {
   "title": "Response time combined (client-side)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.max, 'Upper')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.median, 'Median')"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.2c23-tp-1-node-1.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU')"
    },
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.2c23-tp-1-node-1.memory_usage, 10000000000), 'Memory')"
    }
   ]
  }
 ]
}